<%@ Page Title="Address Book" Language="C#" MasterPageFile="~/Dorknozzle.master" AutoEventWireup="true" CodeFile="AddressBook.aspx.cs" Theme="Blue" Inherits="AddressBook" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1>Address Book</h1>
    <p>
        <button>
            <asp:LinkButton ID="addEMployeeButton" runat="server" Text="Add a New Employee" />
        </button>
    </p>
    <asp:GridView ID="grid" runat="server" AutoGenerateColumns="False" 
        AllowPaging="True" AllowSorting="True" DataKeyNames="EmployeeID" 
        DataSourceID="employeesDataSource" onsorting="grid_Sorting" PageSize="4">
        <Columns>
            <asp:boundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:boundField DataField="City" HeaderText="City" SortExpression="City" />
            <asp:boundField DataField="MobilePhone" HeaderText="Mobile Phone" />
            <asp:ButtonField CommandName="Select" Text="Select" />
        </Columns>
    </asp:GridView><br />
    <asp:DetailsView ID="employeeDetails" runat="server" AutoGenerateRows="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" DataKeyNames="EmployeeID" 
        DataSourceID="employeeDataSource" 
        onitemdeleted="employeeDetails_ItemDeleted" 
        oniteminserted="employeeDetails_ItemInserted" 
        onitemupdated="employeeDetails_ItemUpdated">
        <Fields>
            <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" 
                InsertVisible="False" ReadOnly="True" SortExpression="EmployeeID" />
            <asp:TemplateField HeaderText="Department" SortExpression="DepartmentID">
                <EditItemTemplate>
                    <asp:DropDownList id="didDdl" runat="server" DataSourceID="departmentsDataSource" DataTextField="Department" DataValueField="DepartmentID" SelectedValue='<%# Bind("DepartmentID") %>' />
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server" DataSourceID="departmentsDataSource" DataTextField="Department" DataValueField="DepartmentID" SelectedValue='<%# Bind("DepartmentID") %>' />
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server" DataSourceID="departmentsDataSource" DataTextField="Department" DataValueField="DepartmentID" SelectedValue='<%# Bind("DepartmentID") %>' Enabled="False" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Username" HeaderText="Username" 
                SortExpression="Username" />
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
            <asp:BoundField DataField="Address" HeaderText="Address" 
                SortExpression="Address" />
            <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
            <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
            <asp:BoundField DataField="Zip" HeaderText="Zip" SortExpression="Zip" />
            <asp:BoundField DataField="HomePhone" HeaderText="HomePhone" 
                SortExpression="HomePhone" />
            <asp:BoundField DataField="Extension" HeaderText="Extension" 
                SortExpression="Extension" />
            <asp:BoundField DataField="MobilePhone" HeaderText="MobilePhone" 
                SortExpression="MobilePhone" />
        </Fields>
        <HeaderTemplate>
            <%#Eval("Name") == null ? "Adding New Employee" : Eval("Name")%>
        </HeaderTemplate>
    </asp:DetailsView>
    <asp:SqlDataSource ID="employeesDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        SelectCommand="SELECT [EmployeeID], [Name], [MobilePhone], [City] FROM [Employees] ORDER BY [Name]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="EmployeeDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        DeleteCommand="DELETE FROM [Employees] WHERE [EmployeeID] = @EmployeeID" 
        InsertCommand="INSERT INTO [Employees] ([DepartmentID], [Name], [Username], [Password], [Address], [City], [State], [Zip], [HomePhone], [Extension], [MobilePhone]) VALUES (@DepartmentID, @Name, @Username, @Password, @Address, @City, @State, @Zip, @HomePhone, @Extension, @MobilePhone)" 
        SelectCommand="SELECT [EmployeeID], [DepartmentID], [Name], [Username], [Password], [Address], [City], [State], [Zip], [HomePhone], [Extension], [MobilePhone] FROM [Employees] WHERE ([EmployeeID] = @EmployeeID)" 
        UpdateCommand="UPDATE [Employees] SET [DepartmentID] = @DepartmentID, [Name] = @Name, [Username] = @Username, [Password] = @Password, [Address] = @Address, [City] = @City, [State] = @State, [Zip] = @Zip, [HomePhone] = @HomePhone, [Extension] = @Extension, [MobilePhone] = @MobilePhone WHERE [EmployeeID] = @EmployeeID">
        <DeleteParameters>
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="grid" Name="EmployeeID" 
                PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="departmentsDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        SelectCommand="SELECT [DepartmentID], [Department] FROM [Departments]">
    </asp:SqlDataSource>
</asp:Content>

